version: 2.1

orbs:
  python: circleci/python@0.2.1
  python-lint: qventus/python-lint@0.0.6

jobs:
  test-PyQt5:
    executor: python/default
    steps:
      - checkout
      - python/load-cache:
          key: PyQt5
      - run:
          command: pip install numpy PyQt5 nose
          name: Install Dependencies (PyQt5)
      - python/save-cache
      - run:
          command: nosetests
          environment:
            QT_API: pyqt5
          name: Test (PyQt5)
  
  test-PySide2:
    executor: python/default
    steps:
      - checkout
      - python/load-cache:
          key: PySide2
      - run:
          command: pip install numpy PySide2 nose
          name: Install Dependencies (PySide2)
      - python/save-cache
      - run:
          command: nosetests
          environment:
            QT_API: pyside2
          name: Test (PySide2)

workflows:
  main:
    triggers:
      - schedule:
          filters:
            branches:
              ignore:
                - gh-pages

    jobs:
      - test-PyQt5
      - test-PySide2
      - pylint/lint
